services:
  postgres:
    image: postgres:14-alpine
    container_name: agenda_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '${DB_PORT}:5432'

  backend:
    build: .
    container_name: agenda_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - '${APP_PORT}:3000'
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - APP_PORT=${APP_PORT}
    volumes:
      - ./src:/app/src

volumes:
  postgres_data:
